### ISSUE TITLE
client folder

### ISSUE THREAD

**Issue by msimonc** [rudijs/serverless-websocket-demo#1]
Thanks for this project,

something is wrong with the client folder (shows an arrow...)

can't click into it,

**Comment by rudijs** [comment]
Hey Mark,

This repo is just a backup of me hacking/tinkering around.

I update the code to include the reactjs client - it's also practically nothing just tests the connection.

In the README I've linked to a more complete, but still in complete, serverless app w/ websockets.

A complete app needs: Auth with cognito, then a signIn/Out, then  a connection the a websocket server.

Feel free to follow the links and have a peek - remember though it's just a hacky app, learning and non-prod.
